### ISSUE TITLE
[Feature Request] add a progress bar for BMGInference

### ISSUE THREAD

**Issue by sdementen** [facebookresearch/beanmachine#1314]
### Issue Description

The BMGInference has no progress bar showing the evolution of chain/samples and the duration of each iteration.

### System Info

PyTorch Version (run print(torch.__version__): 1.10.1+cpu
Python version: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]

**Comment by feynmanliang** [comment]
Is this for use in a terminal, Jupyter, or somewhere else?

**Comment by sdementen** [comment]
For the terminal in my use case.
Other inference engines have already this progress bar
