### ISSUE TITLE
Colab & Bokeh persistence

### ISSUE THREAD

**Issue by ndmlny-qs** [facebookresearch/beanmachine#1345]
### Issue Description
Persist Bokeh figures in Colab without having to execute the plot cell.

**Comment by ndmlny-qs** [comment]
In order to persist interactive plots in colab you have to execute the notebook in colab, and then save it to GitHub from Colab. Doing so will persist all types of plots we currently have; matplotlib, plotly, and bokeh.

Thanks @horizon-blue for helping debug this issue.

@michaeltingley We will need someone that has access to save Colab run notebooks to GitHub after their execution. You can see here an example where the notebook has been run in Colab, and then saved to GitHub. The Bokeh plot should be rendered without having to execute the nb.

https://colab.research.google.com/github/ndmlny-qs/bokeh-penguins/blob/main/bokeh_penguins.ipynb

**Comment by ndmlny-qs** [comment]
The downside to doing this is that when notebooks change, we will need to rerun them in Colab, and then save them back to GitHub. @horizon-blue pointed out that this will become tedious, but the current workflow of saving notebooks from Colab to GitHub is a quick work-around for getting the documentation figures to stay rendered.

**Comment by zaxtax** [comment]
Could we diff them to see if we can write a script to add whatever metadata Colab needs to be happy?

**Comment by ndmlny-qs** [comment]
@zaxtax There may be a way to update metadata in the notebook for Colab to render the images. I'll investigate further.

**Comment by ndmlny-qs** [comment]
@horizon-blue @zaxtax Can y'all look at this notebook?

https://colab.research.google.com/github/ndmlny-qs/bokeh-penguins/blob/main/Hierarchical_regression.ipynb

I think I have figured out the mix of metadata needed to display plots without executing cells in Colab.

**Comment by horizon-blue** [comment]
> I think I have figured out the mix of metadata needed to display plots without executing cells in Colab.

That’s awesome! And yes, the plots in that notebook are rendered on my side.

**Comment by ndmlny-qs** [comment]
From this thread, https://github.com/holoviz/holoviews/issues/3551, in order to render Bokeh plots in Colab we have to place the `output_notebook()` call in each cell that has a Bokeh plot in it. This is basically adding an extra output to the cell that contains the Bokeh JavaScript necessary to render the images, which Colab treats as a security feature for cell outputs.

The only way to not have to make this call in each Bokeh cell is to embed the JavaScript needed directly to the cell output in the notebook JSON. We could write a script to do this, but I think just adding the `output_notebook()` call to each cell will be sufficient. The notebook to mdx converter continues to work after adding the `output_notebook()` call in a cell, so we will need to update the notebooks to contain the Bokeh call in them if we want them to render in Colab without execution.
