### ISSUE TITLE
Running chains in parallel

### ISSUE THREAD

**Issue by javiermas** [facebookresearch/beanmachine#1350]
### Issue Description
I would like to be able to run multiple chains in parallel. My understanding is chains are independent of each other, so the task of sampling using multiple chains should be straightforward to parallelise, as other frameworks allow.

I'm surprised this wouldn't be a possibility in beanmachine, but I haven't found a parameter that allows this on the constructors of the inference classes, nor on the infer method of the BaseInference class. Also, I haven't found a reference to this anywhere in the documentation, not even as a limitation. Apologies if this is described somewhere and I'm just not seeing it.

**Comment by jpchen** [comment]
Thanks for the feature request @javiermas! You are right in that chains are perfectly parallel, and so they should be parallelizable across cores. Unfortunately, the serialization that occurs in Python's multiprocessing module to communicate across processes breaks some PyTorch and unit testing functionality, which we are working on fixing, and we hope to support parallelization with [Dask](https://dask.org/) in an upcoming release. Thanks for your patience!

**Comment by horizon-blue** [comment]
Hi @javiermas, with #1369 we have added [an `run_in_parallel` arguments to `infer`](https://github.com/facebookresearch/beanmachine/blob/main/src/beanmachine/ppl/inference/base_inference.py#L177-L178) that can be used to control whether chains should be run in subprocess or not. This will be available in our next release, which is expected to come in April. You can follow our [instruction](https://github.com/facebookresearch/beanmachine#install-from-source) to install BM from source if you'd like to try this out sooner :).
