### ISSUE TITLE
discussions feature

### ISSUE THREAD

**Issue by ndmlny-qs** [facebookresearch/beanmachine#1464]
@horizon-blue can we add the GitHub dissucsions feature to the repo?

https://docs.github.com/en/discussions/quickstart

I'd like to begin a discussion around the issues #1348 #1428 #1406 as they are all related and depend on a dev release of Bokeh for them to work.

**Comment by horizon-blue** [comment]
That's a great suggestion. I will discuss with the team to see if people have any concern about turning on this feature :).

**Comment by feynmanliang** [comment]
To summarize today's mtg conclusions

        * Current concern is that having this feature will open us up to more support responsibilities
        * Once we have more planning completed, we will revisit this issue — in coming few weeks

Mind if we close this for now and re-open later?
