### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by noamsgl** [facebookresearch/beanmachine#1516]
I was hoping to try but my university clusters are so old.

**What do I need to update and how?**

I don't have sudo. I only have write access to /home/my_username/

Thanks!

 > pip install -e ".[dev]" 

![image](https://user-images.githubusercontent.com/44804339/176270024-f5efd1cc-19cc-4125-b42e-3bd48cfe90cc.jpeg)

![image](https://user-images.githubusercontent.com/44804339/176270036-929ebb2b-59ef-43dd-b1b3-2fa66d244708.jpeg)

**Comment by ndmlny-qs** [comment]
What version of `gcc` is installed on the machine? You can find this by running `gcc --version` and posting the output here

**Comment by noamsgl** [comment]
The version is 4.8.5

```
-bash-4.2$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

Thanks for your help!

**Comment by ndmlny-qs** [comment]
Unfortunately Bean Machine will not compile with that version of `gcc`, although you may have better luck with the library in Google Colab at any rate. Check out the tutorials at https://beanmachine.org/docs/overview/tutorials/Coin_flipping/CoinFlipping/ and click on the Colab link at the top of the page of any tutorial. Colab will install Bean Machine correctly, and you will see how to use the library interactively there.

**Comment by horizon-blue** [comment]
In addition to what @ndmlny-qs says, even though you can't build Bean Machine from source with your gcc version, you should be able to install prebuilt Bean Machine wheels from PyPI just fine with `pip install beanmachine`

**Comment by noamsgl** [comment]
Thanks @ndmlny-qs @horizon-blue
