### ISSUE TITLE
HTML Comment Unintentionally Showing in Coin Flipping Tutorial 

### ISSUE THREAD

**Issue by JiahuiKChen** [facebookresearch/beanmachine#1553]
### Issue Description
In the [Analysis section](https://beanmachine.org/docs/overview/tutorials/Coin_flipping/CoinFlipping/#analysis) of the [Coin flipping tutorial](https://beanmachine.org/docs/overview/tutorials/Coin_flipping/CoinFlipping/), there's a code snippet showing what looks like an HTML comment:
<img width="999" alt="image" src="https://user-images.githubusercontent.com/25305208/179816020-4b9706fa-91ff-4dc6-b41a-484b91f98885.png">

### Steps to Reproduce
Go to the [page](https://beanmachine.org/docs/overview/tutorials/Coin_flipping/CoinFlipping/#analysis), scroll down.

**Comment by horizon-blue** [comment]
Thanks for the bug report. Looks like this is a bug in our ipynb to mdx conversion script. @ndmlny-qs, do you mind taking a look?

**Comment by ndmlny-qs** [comment]
Sure, I know what the problem is and will fix. Having comments in MD is useful and I recall there is a way to preserve them when converting from a notebook to mdx, so I'll make sure it's documented on how to do it.
