### ISSUE TITLE
Arviz diagnostics plots do not properly handle non-scalar random variables

### ISSUE THREAD

**Issue by feynmanliang** [facebookresearch/beanmachine#1563]
### Issue Description
When I make trace plots of a vector-valued RV, from the [arviz docs](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_trace.html) I would expect one trace plot per dimension
because each KDE is 1D. However, the current behavior lumps them all together into one.

### Steps to Reproduce
```
import beanmachine.ppl as bm
import torch.distributions as dist
import arviz as az
foo = bm.random_variable(lambda: dist.MultivariateNormal(torch.zeros(4), torch.eye(4)))
xx = bm.SingleSiteRandomWalk().infer(queries=[foo()], observations={}, num_samples=100, num_chains=2)
az.plot_trace(xx.to_inference_data())
```

produces the following plot:

![image](https://user-images.githubusercontent.com/990069/180610840-561c9d26-3f51-4c8d-b63e-695f92206bfc.png)

### Expected Behavior

Four separate trace plots, one for each of the dimensions of `foo`.

**Comment by zaxtax** [comment]
I'll look into this!

**Comment by zaxtax** [comment]
I think the desired behaviour comes from passing `compact=False` to `az.plot_trace`

![](file:///home/zv/Figure_1.png)

**Comment by zaxtax** [comment]
@feynmanliang does this adequately address your concerns?

**Comment by feynmanliang** [comment]
Yes, this is my lack of understanding of Arviz APIs. Thank you :)
