### ISSUE TITLE
BNN with ADVI tutorial does not display predictions/confidence

### ISSUE THREAD

**Issue by feynmanliang** [facebookresearch/beanmachine#1657]
### Issue Description
The last cell of https://beanmachine.org/docs/overview/tutorials/Bayesian_NNs_with_ADVI/BayesianNnsWithAdvi/ references a figure to be drawn via a a `show` command, but no figure is displayed

### Steps to Reproduce
Go to https://beanmachine.org/docs/overview/tutorials/Bayesian_NNs_with_ADVI/BayesianNnsWithAdvi/

### Expected Behavior
A figure is shown under the last code cell showing the predictions and uncertainty

**Comment by feynmanliang** [comment]
This might be due the newline?

**Comment by zaxtax** [comment]
I think so.

**Comment by horizon-blue** [comment]
Closing this issue since the rendering of the tutorial is fixed with #1661
