### ISSUE TITLE
[Feature Request] Support NNC/torchinductor usage in gpytorch + GlobalNUTS integration

### ISSUE THREAD

**Issue by feynmanliang** [facebookresearch/beanmachine#1665]
### Issue Description

We have [a prototype integration of GlobalNUTS with gpytorch](https://colab.research.google.com/drive/1nB0-SBHb38xrr1gyT_63a883CDxEQtpO?usp=sharing) which I would like to accelerate with NNC.

### Steps to Reproduce

Execute the cell with `nnc_compile=True`. It raises the following

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-136-2558f70fe3a8>](https://localhost:8080/#) in <module>
      7     num_samples=10,
      8     num_adaptive_samples=10,
----> 9     num_chains=1,
     10 )

9 frames
[/usr/local/lib/python3.7/dist-packages/beanmachine/ppl/inference/base_inference.py](https://localhost:8080/#) in infer(self, queries, observations, num_samples, num_chains, num_adaptive_samples, show_progress_bar, initialize_fn, max_init_retries, run_in_parallel, mp_context, verbose)
    210                 chain_results = p.starmap(single_chain_infer, enumerate(seeds))
    211 
--> 212         all_samples, all_log_liklihoods = zip(*chain_results)
    213         # the hash of RVIdentifier can change when it is being sent to another process,
    214         # so we have to rely on the order of the returned list to determine which samples

[/usr/local/lib/python3.7/dist-packages/beanmachine/ppl/inference/base_inference.py](https://localhost:8080/#) in _single_chain_infer(self, queries, observations, num_samples, num_adaptive_samples, show_progress_bar, initialize_fn, max_init_retries, chain_id, seed)
    109             desc="Samples collected",
    110             disable=not show_progress_bar,
--> 111             position=chain_id,
    112         ):
    113             for idx, obs in enumerate(observations):

[/usr/local/lib/python3.7/dist-packages/tqdm/notebook.py](https://localhost:8080/#) in __iter__(self)
    257         try:
    258             it = super(tqdm_notebook, self).__iter__()
--> 259             for obj in it:
    260                 # return super(tqdm...) will not catch exception
    261                 yield obj

[/usr/local/lib/python3.7/dist-packages/tqdm/std.py](https://localhost:8080/#) in __iter__(self)
   1193 
   1194         try:
-> 1195             for obj in iterable:
   1196                 yield obj
   1197                 # Update and possibly print the progressbar.

[/usr/lib/python3.7/_collections_abc.py](https://localhost:8080/#) in __next__(self)
    315         When exhausted, raise StopIteration.
    316         """
--> 317         return self.send(None)
    318 
    319     @abstractmethod

[/usr/local/lib/python3.7/dist-packages/beanmachine/ppl/inference/sampler.py](https://localhost:8080/#) in send(self, world)
     73         for proposer in proposers:
     74             try:
---> 75                 new_world, accept_log_prob = proposer.propose(world)
     76                 accept_log_prob = accept_log_prob.clamp(max=0.0)
     77                 accepted = torch.rand_like(accept_log_prob).log() < accept_log_prob

[/usr/local/lib/python3.7/dist-packages/beanmachine/ppl/inference/proposer/nuts_proposer.py](https://localhost:8080/#) in propose(self, world)
    307             )
    308             if direction == -1:
--> 309                 new_tree = self._build_tree(tree.left, j, tree_args)
    310             else:
    311                 new_tree = self._build_tree(tree.right, j, tree_args)

[/usr/local/lib/python3.7/dist-packages/beanmachine/ppl/inference/proposer/nuts_proposer.py](https://localhost:8080/#) in _build_tree(self, root, tree_depth, args)
    157         combine the two."""
    158         if tree_depth == 0:
--> 159             return self._build_tree_base_case(root, args)
    160 
    161         # build the first half of the tree

[/usr/local/lib/python3.7/dist-packages/functorch/_src/aot_autograd.py](https://localhost:8080/#) in returned_function(*args, **kwargs)
    426         # Now flatten the tensor args
    427         if HAS_TREE:
--> 428             flat_tensor_args = tree.flatten((tensor_args, kwargs))
    429         else:
    430             flat_tensor_args, _ = pytree.tree_flatten((tensor_args, kwargs))

[/usr/local/lib/python3.7/dist-packages/tree/__init__.py](https://localhost:8080/#) in flatten(structure)
    225     TypeError: If `structure` is or contains a mapping with non-sortable keys.
    226   """
--> 227   return _tree.flatten(structure)
    228 
    229 

TypeError: '<' not supported between instances of 'RVIdentifier' and 'RVIdentifier'
```

### Expected Behavior

A faster run of NNC

### System Info
Please provide information about your setup
- PyTorch Version (run `print(torch.__version__)` 1.12.1+cu113
- Python version: 3.9
- Beanmachine version: 0.2.0

**Comment by horizon-blue** [comment]
Hi Feynman, it looks to me that this particular error actually doesn't have anything to do with GPytorch. You're seeing this because [functorch 0.2.1 wants to sort the keys of a dictionary before flattening it](https://github.com/pytorch/functorch/blob/v0.2.1/functorch/_src/aot_autograd.py#L42). We actually [overrode this behavior in BM in our nnc utils](https://github.com/facebookresearch/beanmachine/blob/main/src/beanmachine/ppl/inference/proposer/nnc/utils.py#L26-L37), but it looks like for whatever reason this override is not working here. So, as a workaround, you can try defining the `<` operator for `RVIdentifier` so they are sortable, by adding the following snippet to your notebook:

```python
bm.RVIdentifier.__lt__ = lambda self, other: hash(self) < hash(other)
```

Could you give this a try to see if this fixes the error for you?

As a side note, in the latest functorch, [they've removed the sorting of keys](https://github.com/pytorch/pytorch/pull/83137/files), so this should no longer be an issue for us.

**Comment by feynmanliang** [comment]
The ordering doesn't seem stable; here's what happens:

```
# temporary hack for NNC
bm.RVIdentifier.__lt__ = lambda self, other: hash(self) < hash(other)

samples = bm.GlobalNoUTurnSampler(nnc_compile=True).infer(
    queries=queries,
    observations={
        x(): train_x,
        y(): train_y,
    },
    num_samples=10,
    num_adaptive_samples=10,
    num_chains=1,
)
```
results in
```
Samples collected: 100%
20/20 [00:10<00:00, 2.27it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-151-6511cc23ed77>](https://localhost:8080/#) in <module>
     90     num_samples=10,
     91     num_adaptive_samples=10,
---> 92     num_chains=1,
     93 )

2 frames
[/usr/local/lib/python3.7/dist-packages/beanmachine/ppl/inference/base_inference.py](https://localhost:8080/#) in <listcomp>(.0)
    122                 samples[idx].append(raw_val)
    123 
--> 124         samples = [torch.stack(val) for val in samples]
    125         log_likelihoods = [torch.stack(val) for val in log_likelihoods]
    126         return samples, log_likelihoods

RuntimeError: stack expects each tensor to be equal size, but got [1] at entry 0 and [1, 1] at entry 3
```

Inserting https://github.com/facebookresearch/beanmachine/blob/main/src/beanmachine/ppl/inference/proposer/nnc/utils.py#L26-L37 as a cell also does not have an effect.

I tried install functorch from head, but it depends on torch 1.13.0.dev and ignoring dependencies results in a compile error.

**Comment by horizon-blue** [comment]
> The sort ordering of keys doesn't seem stable

That's a good catch. Does using a stable definition of `__lt__` solve the issue? e.g.

```python
bm.RVIdentifier.__lt__ = lambda self, other: str(self) < str(other)
```

> I tried install functorch from head, but it depends on torch 1.13.0.dev

You can try installing torch 1.13.0.dev from the nightly channel, though from my past experience building functorch from source can be tricky since it's is being updated on daily basis, and sometimes even if you install the nightly torch, it can still be off-sync from the latest functorch.

**Comment by feynmanliang** [comment]
Yes, this works :)
![image](https://user-images.githubusercontent.com/990069/190017366-7e88667c-d9cc-4da0-be89-f19dd220ea72.png)
![image](https://user-images.githubusercontent.com/990069/190017452-643365f4-626f-4314-9962-9e0ee5eda86f.png)

and it appears to be significantly faster than Pyro for the same model / results
![image](https://user-images.githubusercontent.com/990069/190017426-14c580a3-ef5d-4f06-b10a-2a8d1e106661.png)
![image](https://user-images.githubusercontent.com/990069/190017467-80530301-e1a1-4f3a-a06d-7779eaccccec.png)

CC @eytan @Balandat @dme65, and I will evaluate and document the comparison in an internal doc as well.

Do we think it'll be OK to override ordering on RVIdentifier until functorch cuts a new release? If so, we can close this issue.

**Comment by horizon-blue** [comment]
Glad to see the fast performance of BM + NNC :D.

> Do we think it'll be OK to override ordering on RVIdentifier until functorch cuts a new release?

Sure, I'm working on D39486353 that add `__lt__` to `RVIentifier` for now and will create a PR once the tests pass. You might be able to use BM+NNC even without this patch internally, though, since Buck always uses the latest source code. :)
